export const fallbackRelays = [
  'wss://relay.damus.io',
  'wss://nostr-pub.wellorder.net',
  'wss://offchain.pub',
  'wss://nostr.fmt.wiz.biz',
  'wss://eden.nostr.land',
  'wss://atlas.nostr.land',
  'wss://relay.snort.social',
  'wss://nostr.fly.dev',
  'wss://nostr.nostr.band',
  'wss://relay.nostrgraph.net',
  'wss://relay.nostr.bg',
  'wss://nostr.wine',
  'wss://nos.lol',
  'wss://relay.mostr.pub',
  'wss://no.str.cr',
  'wss://brb.io',
  'wss://nostr.zebedee.cloud'
]